### PR TITLE
add support to send frame larger than 125 bytes

### PR DESCRIPTION
**Pull request by diegocardoso93**

### CODE REVIEW

**Comment by chilipeppr** [comment]
Hi diegocardoso93,

I looked through the code and it looks like you didn't have to change too much to get it to support >126 chars. Is that really all it took? I thought it was more complicated than that. Are you sure if I merge this pull request that we didn't break anything? I don't have a great way to test it right now, so curious what your test results were?

**Comment by diegocardoso93** [comment]
Hey chilipeppr!

First, thank you so much for this script, you are amazing!
Oh, sorry, yes, incredible as it seems to be working properly for me.


**Let's look test codes**
------------
**Lua test code [file esp32_websocket_example.lua] (supressed wi-fi ap config):**
```
-- ChiliPeppr Websocket for ESP32 test
-- Visit http://chilipeppr.com/esp32 for more details

ws = require('esp32_websocket')
ws.on("receive", function(data, fin)
  -- fin of 1 or nil means you got all data
  -- fin of 0 means extended data will come in
  print("Got data:" .. data .. ", fin:", fin)
end)
ws.on("connection", function(host, port, path)
  print("Websocket connected to host:", host, "port:", port, "path:", path)
  ws.send("list") -- teste < 126
  local buffSend = ""
  for i=0, 100, 1 do
	buffSend = buffSend .. "ABCDE"
  end
  ws.send(buffSend) -- teste > 126
end)
ws.on("disconnection", function()
  print("Websocket got disconnect from:", ws.wsUrl)
end)
ws.on("pingsend", function()
  print("Ping")
end)
ws.on("pongrecv", function()
  print("Got pong. We're alive.")
end)
ws.connect("ws://192.168.4.2:9061/")
```

**Node.js ws server:**
```
const WebSocket = require('ws');
const express = require('express');
const path = require('path');
const app = express();
const server = require('http').createServer();

app.use(express.static(path.join(__dirname, '/')));

const wss = new WebSocket.Server({server: server});

wss.on('connection', function (ws) {

  ws.on('message', function incoming(data) {
	console.log(data.length, data)
	wss.clients.forEach(function each(client) {
	  if (client !== ws && client.readyState === WebSocket.OPEN) {
		client.send(data);
	  }
	});
  });

});

server.on('request', app);
server.listen(9061, function () {
  console.log('Listening on http://localhost:9061');
});

```

**NodeMCU outputs:**
```
sta connected
dofile("esp32_websocket_example.lua")
Websocket connecting to:	192.168.4.2	port:	9061	path:	/
> GET / HTTP/1.1

Host: 192.168.4.2

Upgrade: websocket

Connection: Upgrade

Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==

Sec-WebSocket-Protocol: chat, superchat

Sec-WebSocket-Version: 13

Origin: esp32


Websocket found hdr
Websocket connected to host:	192.168.4.2	port:	9061	path:	/
Websocket doing send. data:	list
Websocket doing send. data:	ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE
Ping
Got pong. We're alive.
Ping
Got pong. We're alive.
```


Server outputs:
```
Listening on http://localhost:9061
4 'list'
505 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE'

```

As you see the server received the 505 char length string correctly. And did not break 'list' test word.

**Comment by chilipeppr** [comment]
Awesome. This looks great.

**Comment by chilipeppr** [comment]
Just did the merge. What happens if the payload is less than 126 bytes. Is it still ok?

**Comment by diegocardoso93** [comment]
@chilipeppr Yes, in the example above I tested the word "list" too, that contains 4 characters and all still ok.

**Pull request merged**
